#! /usr/bin/env python3
# -*- coding: utf-8 -*-

"""# yamlfixer
yamlfixer automates the fixing of problems reported by
[yamllint](https://github.com/adrienverge/yamllint) by parsing its
output.

# Usage
This software automatically fixes some errors and warnings reported by
yamllint.

usage:

```
$ yamlfixer [--debug] [--verbose] *.yml - thisfile.yaml
```

or:

```
$ yamlfixer [--help] [--version]
```

This will launch yamllint on each specified file name (`-` is _stdin_),
then parse its output and try to fix problems reported by passing this file
through _yamllint_.

If input is read from _stdin_, the corrected output will be sent to
_stdout_. Other files will be overwritten if needed.

Diagnostic information is sent to stderr in verbose or debug modes.

This command exits with `0` if all input files either are skipped or
successfully pass _yamllint_ strict mode, else `-1`.

**IMPORTANT:** Not all problems are fixable by _yamlfixer_. Due to the way
[yamllint](https://github.com/adrienverge/yamllint) works, it doesn't
currenlty report all faulty lines, _yamlfixer_ might even introduce
indentation problems under some circumstances.
**Use at your own risk, you have been warned...**

# Licensing information
Copyright (C) 2021 OPT-NC

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Contact

OPT-NC, aka _Office des Postes et Télécommunications de Nouvelle-Calédonie_,
has a corporate website on [www.opt.nc](https://www.opt.nc)

You can contact the author of this software at
[jerome.alet@opt.nc](mailto:jerome.alet@opt.nc)
"""

import sys
import os
import subprocess

VERSION = '0.1'

LINTERCOMMAND = 'yamllint --format parsable --strict -'

FIX_PASSEDLINTER = 0
FIX_MODIFIED = 1
FIX_UNMODIFIED = 2
FIX_SKIPPED = 3
FIX_PERMERROR = 4

FIXER_UNHANDLED = -1
FIXER_HANDLED = 0

class ProblemFixer:
    """To hold problem fixing logic."""
    fixers = {}
    def __init__(self, filefixer, linenum, colnum, problem):
        """Intializes a problem fixer."""
        self.filefixer = filefixer
        self.linenum = linenum + self.filefixer.loffset - 1
        self.colnum = colnum + self.filefixer.coffset - 1
        self.problem = problem
        if not self.fixers:
            for methodname in [m for m in dir(self) if m.startswith('fix_')]:
                docstring = getattr(self, methodname).__doc__
                for prob in [pb.strip()[2:] for pb in docstring.splitlines()[1:]]:
                    if prob:
                        self.fixers[prob] = methodname

    def __call__(self):
        """Make it callable."""
        for (fixerkey, methodname) in self.fixers.items():
            if self.problem.startswith(fixerkey):
                # pylint: disable=line-too-long
                self.filefixer.parent.debug(f"Calling {methodname} because [{fixerkey}] matches [{self.problem}]")
                getattr(self, methodname)()
                return FIXER_HANDLED
        self.filefixer.parent.debug(f"No handler found for [{self.problem}]")
        return FIXER_UNHANDLED

    def get_indentation(self, offset):
        """Returns the indentation of the specified line."""
        line = self.filefixer.lines[self.linenum + offset]
        return len(line) - len(line.lstrip())

    def fix_missing_docstart(self):
        """Fix:
             - missing document start
        """
        self.filefixer.lines.insert(0, '---')
        self.filefixer.loffset += 1

    def fix_truthy(self):
        """Fix:
             - truthy value should be one of [false, true] (truthy)
        """
        for trueval in ('on', 'yes', 'true'):
            if self.filefixer.lines[self.linenum][self.colnum:].lower().startswith(trueval):
                # pylint: disable=line-too-long
                self.filefixer.lines[self.linenum] = self.filefixer.lines[self.linenum][:self.colnum] \
                    + 'true' + self.filefixer.lines[self.linenum][self.colnum + len(trueval):]
                self.filefixer.coffset += len('true') - len(trueval)
                return
        for falseval in ('off', 'no', 'false'):
            if self.filefixer.lines[self.linenum][self.colnum:].lower().startswith(falseval):
                # pylint: disable=line-too-long
                self.filefixer.lines[self.linenum] = self.filefixer.lines[self.linenum][:self.colnum] \
                    + 'false' + self.filefixer.lines[self.linenum][self.colnum + len(falseval):]
                self.filefixer.coffset += len('false') - len(falseval)
                return

    def fix_toofew_spacesbefore(self):
        """Fix:
             - too few spaces before comment (comments)
        """
        spaces = ' '
        if self.filefixer.lines[self.linenum][self.colnum - 1] != ' ':
            spaces += ' '
        self.filefixer.lines[self.linenum] = self.filefixer.lines[self.linenum][:self.colnum] \
            + spaces + self.filefixer.lines[self.linenum][self.colnum:]
        self.filefixer.coffset += len(spaces)

    def fix_trailingspaces(self):
        """Fix:
             - trailing spaces (trailing-spaces)
        """
        # No need to adjust coffset because we are at EOL by definition
        self.filefixer.lines[self.linenum] = self.filefixer.lines[self.linenum].rstrip()

    def fix_toomany_blanklines(self):
        """Fix:
             - too many blank lines
        """
        parts = self.problem.split()
        blanklines = int(parts[4][1:])
        maxblanklines = int(parts[6].split(')')[0])
        nblines = blanklines - maxblanklines
        del self.filefixer.lines[self.linenum - nblines + 1:self.linenum + 1]
        self.filefixer.loffset -= nblines

    def fix_syntax_tabchar(self):
        """Fix:
             - syntax error: found character '\\t' that cannot start any token (syntax)
        """
        # TODO: We replace TAB with a single space for now
        # TODO: yamllint only reports the first one
        self.filefixer.lines[self.linenum] = self.filefixer.lines[self.linenum][:self.colnum] \
            + ' ' + self.filefixer.lines[self.linenum][self.colnum + 1:]

    def fix_missingspace(self):
        """Fix:
             - missing starting space in comment (comments)
             - too few spaces after comma (commas)
        """
        self.filefixer.lines[self.linenum] = self.filefixer.lines[self.linenum][:self.colnum] \
            + ' ' + self.filefixer.lines[self.linenum][self.colnum:]
        self.filefixer.coffset += 1

    def fix_toomany_spacesafter(self):
        """Fix:
             - too many spaces after colon (colons)
             - too many spaces after comma (commas)
             - too many spaces after hyphen (hyphens)
        """
        pos = self.colnum
        while (pos > 0) and (self.filefixer.lines[self.linenum][pos - 1] == ' '):
            pos -= 1
        self.filefixer.lines[self.linenum] = self.filefixer.lines[self.linenum][:pos] \
            + self.filefixer.lines[self.linenum][self.colnum:]
        self.filefixer.coffset -= (self.colnum - pos)

    def fix_toomany_spacesother(self):
        """Fix:
             - too many spaces inside braces (braces)
             - too many spaces inside brackets (brackets)
             - too many spaces before comma (commas)
             - too many spaces before colon (colons)
        """
        pos = self.colnum
        while (pos > 0) and (self.filefixer.lines[self.linenum][pos - 1] == ' '):
            pos -= 1
        self.filefixer.lines[self.linenum] = self.filefixer.lines[self.linenum][:pos] \
            + self.filefixer.lines[self.linenum][self.colnum + 1:]
        self.filefixer.coffset -= (self.colnum - pos + 1)

    def fix_comment_notindentedlike(self):
        """Fix:
             - comment not indented like content (comments-indentation)
        """
        if self.linenum > 0:
            indentation = self.get_indentation(-1)
            # If previous line is similarly indented then use indentation of next line
            if indentation == self.colnum:
                indentation = self.get_indentation(+1)
        else:
            indentation = self.get_indentation(+1)
        self.filefixer.lines[self.linenum] = ' ' * indentation \
            + self.filefixer.lines[self.linenum].lstrip()
        self.filefixer.coffset += (indentation - self.colnum)

    def fix_wrong_indentation(self):
        """Fix:
             - wrong indentation: expected
        """
        # TODO: yamllint only reports the first faulty line in a block :-(
        # TODO: see https://github.com/adrienverge/yamllint/issues/427
        # TODO: we fix anyway, knowing that we may need to launch the command
        # TODO: several times to finally fix the problem.
        parts = self.problem.split()
        expected = int(parts[3])
        found = int(parts[6])
        offset = expected - found
        if expected > found:
            self.filefixer.lines[self.linenum] = (' ' * offset) \
                + self.filefixer.lines[self.linenum]
        else:
            # expected < found because we woudln't be there otherwise anyway
            self.filefixer.lines[self.linenum] = self.filefixer.lines[self.linenum][-offset:]
        self.filefixer.coffset += offset

    def fix_linetoolong(self):
        """Fix:
             - line too long
        """
        # TODO: currently we fix this by disabling the error in yamllint, it's the easiest way
        self.filefixer.lines.insert(self.linenum, ' ' * self.get_indentation(0) \
                                    + '# yamllint disable-line rule:line-length')
        self.filefixer.loffset += 1


class FileFixer:
    """To hold file fixing logic."""
    def __init__(self, yamlfixer, filename):
        """Initialize a file to fix."""
        self.parent = yamlfixer
        self.filename = filename
        self.loffset = self.coffset = 0
        self.shebang = ''
        self.incontents = None
        self.lines = []

    def lint(self):
        """Launches the linter on a file's contents.

           Returns the (linter's exitcode, linter's stdout) tuple.
        """
        linter = subprocess.run(LINTERCOMMAND,
                                shell=True,
                                capture_output=True,
                                text=True,
                                check=False,
                                input=self.incontents,
                                encoding='utf-8')
        return (linter.returncode, linter.stdout)

    def load(self):
        """Loads the input file's contents."""
        if self.filename == '-':
            self.incontents = sys.stdin.read()
        else:
            try:
                with open(self.filename, 'r') as yamlfile:
                    self.incontents = yamlfile.read()
            except FileNotFoundError as msg:
                sys.stderr.write(f"{msg}\n")

    def dump(self, outcontents):
        """Dumps the new file's contents."""
        if (self.incontents is None) or (outcontents == self.incontents):
            retcode = FIX_SKIPPED
        else:
            retcode = FIX_MODIFIED
        if self.filename == '-': # Always dump to stdout in this case
            sys.stdout.write(self.shebang + (outcontents or ''))
            sys.stdout.flush()
        elif retcode == FIX_MODIFIED: # Don't write unnecessarily
            try:
                with open(self.filename, 'w') as yamlfile:
                    yamlfile.write(self.shebang + (outcontents or ''))
            except PermissionError as msg:
                sys.stderr.write(f"{msg}\n")
                retcode = FIX_PERMERROR
        return retcode

    def fix(self):
        """Fix a file's contents."""
        # Load the file's contents in memory
        self.load()

        # Skip that file if we don't want to modify it
        if (self.incontents is None) or self.incontents.startswith('$ANSIBLE_VAULT;'):
            return self.dump(self.incontents)

        # Lint the file's contents
        (ltexitcode, ltstdout) = self.lint()
        if not ltexitcode:
            self.dump(self.incontents)
            return FIX_PASSEDLINTER

        # Create a nested mapping of lines and columns to fix
        linestofix = {}
        for line in ltstdout.splitlines():
            (_, linenumber, colnumber, message) = line.split(':', 3)
            (_, msg) = message.strip().split(' ', 1)
            colstofix = linestofix.setdefault(int(linenumber), {})
            # On a given line, there could be several problems on the same column
            coltofix = colstofix.setdefault(int(colnumber), [])
            coltofix.append(msg)

        # If there's a shebang line we ignore it and any problem reported on it
        if (self.incontents is not None) and self.incontents.startswith('#!'):
            eolpos = self.incontents.find('\n') + 1
            self.shebang = self.incontents[:eolpos]
            self.incontents = self.incontents[eolpos:]
            try:
                del linestofix[1]
            except KeyError:
                pass # No problem reported on shebang line by yamllint
            # This line won't ever see the fixer so all subsequent lines must be offset by -1
            self.loffset = -1

        # Now handle each of the problems reported by yamllint
        self.lines = self.incontents.splitlines()
        for linenumber in sorted(linestofix.keys()):
            self.coffset = 0
            for colnumber in sorted(linestofix[linenumber].keys()):
                for problem in linestofix[linenumber][colnumber]:
                    # pylint: disable=line-too-long
                    debuginfo = f"({linenumber}, {colnumber})/({self.loffset}, {self.coffset}) => {problem}"
                    handled = ProblemFixer(self, linenumber, colnumber, problem)()
                    # pylint: disable=line-too-long
                    self.parent.debug(f"{((handled == FIXER_HANDLED) and 'HANDLED') or 'UNHANDLED'}: {debuginfo}")
        return self.dump('\n'.join(self.lines) + '\n')


class YAMLFixer:
    """To hold files fixing logic."""
    def __init__(self, arguments):
        """Initialize the fixer for all files."""
        for mode in ('verbose', 'debug'):
            attribute = f"{mode}mode"
            option = f"--{mode}"
            if option in arguments:
                setattr(self, attribute, True)
                arguments.remove(option)
            else:
                setattr(self, attribute, False)
        self.filenames = arguments
        if not self.filenames:
            self.filenames.append("-") # Add fake input from stdin
        self.passed = self.modified = self.unmodified = self.skipped = self.permerrors = 0

    def info(self, message, newline=True):
        """Output an informational message to stderr if verbose mode is active."""
        if self.verbosemode: # pylint: disable=no-member
            sys.stderr.write(f"{message}")
            if newline:
                sys.stderr.write('\n')

    def debug(self, message):
        """Output a debug message to stderr if debug mode is active."""
        if self.debugmode: # pylint: disable=no-member
            sys.stderr.write(f"DEBUG: {message}\n")

    def error(self, message): # pylint: disable=no-self-use
        """Output an error message to stderr."""
        sys.stderr.write(f"ERROR: {message}\n")

    def statistics(self):
        """Output some statistics."""
        self.info(f"Files to fix: {len(self.filenames)}")
        self.info(f"{self.passed} files passed yamllint strict mode")
        self.info(f"{self.modified} files were modified")
        self.info(f"{self.unmodified} files were left unmodified")
        self.info(f"{self.skipped} files were skipped")
        self.info(f"{self.permerrors} files were not writeable")

    def fix(self):
        """Fix all files."""
        for filename in self.filenames:
            if filename == '-':
                absfilename = '<stdin>'
            else:
                absfilename = os.path.abspath(filename)
            filetofix = FileFixer(self, filename)
            # pylint: disable=no-member
            self.info(f"Fixing {absfilename} ... ", newline=False or self.debugmode)
            status = filetofix.fix()
            if status == FIX_PASSEDLINTER:
                self.info(f"passed linter's strict mode.")
                self.passed += 1
            elif status == FIX_MODIFIED:
                self.info(f"was modified.")
                self.modified += 1
            elif status == FIX_UNMODIFIED:
                self.info(f"was left unmodified.")
                self.unmodified += 1
            elif status == FIX_SKIPPED:
                self.info(f"was skipped.")
                self.skipped += 1
            elif status == FIX_PERMERROR:
                self.info(f"was not writeable.")
                self.permerrors += 1
            else:
                self.error(f"unknown fixing status [{status}]")

        self.statistics()
        if (self.passed + self.skipped) == len(self.filenames):
            return 0
        return -1

def main(arguments):
    """Main function."""
    if '--help' in arguments:
        print(__doc__)
        return 0
    if '--version' in arguments:
        print(f"yamlfixer v{VERSION}")
        return 0
    fixer = YAMLFixer(arguments)
    return fixer.fix()

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
