---
name: Docker Image CI

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main, devel]
  release:
    types: [published]

jobs:
  build_and_publish_on_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Prepare tags
        id: prep
        run: |
          DOCKER_IMAGE=optnc/yamlfixer
          VERSION=noop
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            TAGS="${DOCKER_IMAGE}:latest,${DOCKER_IMAGE}:stable,${DOCKER_IMAGE}:${VERSION}"
          else
            TAGS="${DOCKER_IMAGE}:latest"
          fi
          echo ::set-output name=tags::${TAGS}
      - name: Login to DockerHub
        uses: docker/login-action@v1.12.0
        with:
          username: ${{secrets.OPT_DOCKERHUB_LOGIN}}
          password: ${{secrets.OPT_DOCKERHUB_PASSWORD}}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.8.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.prep.outputs.tags }}
